[package]
name = "spell"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@elementai.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
pretty_assertions = "0.5"
